name: Test Installation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-installation:
    runs-on: [macos-latest, ubuntu-latest] 

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    # Step 2: Set up Miniconda 
    - name: Set Up Python 
      uses: conda-incubator/setup-miniconda@v2 
      with:
        python-version: "3.9"
   
    # Step 3: Install dependencies 
    - name: Create and Activate Conda Environment
      run: |
        conda env create -f environment.yml
        conda activate py39
    
    # Step 4: Verify installation
    - name: Verify Dependencies 
      run: |
        python -c "import numpyro, scipy, matplotlib, numpy, jax; print('Dependencies installed')"
    
    # Step 5: Run tests
